name: Firebase

on:
  push:
    branches:
    - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10.x
    - run: cd functions; npm install; cd ..
    - uses: w9jds/firebase-action@master
      with:
        args: functions:config:set domain="${{ secrets.FIREBASE_DOMAIN }}" api_key="${{ secrets.FIREBASE_API_KEY }}"
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions --project ${{ secrets.FIREBASE_DOMAIN }}
