name: Firebase

on:
  push:
    branches:
    - master
jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: 10.x
    - run: cd functions; npm install; cd ..
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions --project ${{ secrets.FIREBASE_DOMAIN }}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        SENDGRID_LIST_ID: ${{ secrets.SENDGRID_LIST_ID }}
        SENDGRID_CORS_ORIGIN: ${{ secrets.SENDGRID_CORS_ORIGIN }}
